apiVersion: keda.sh/v1alpha1
kind: ScaledObject

metadata:
  name: notification-worker-scaler
  namespace: eventhub

spec:
  scaleTargetRef:
    name: notification-worker

  pollingInterval: 5
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 5

  triggers:
    - type: redis-streams
      metadata:
        address: redis.eventhub.svc.cluster.local:6379
        stream: notifications
        consumerGroup: notification-workers
        pendingEntriesCount: "1"
        activationPendingEntriesCount: "0"