apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: eventhub

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: capstone_event_ticketingandvenueaccess-backend:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3000

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          env:
            - name: DB_HOST
              value: mysql

            - name: DB_PORT
              value: "3306"

            - name: DB_NAME
              value: eventhub

            - name: DB_USER
              value: root

            - name: DB_PASSWORD
              value: "Ishu@12345"

            - name: REDIS_HOST
              value: redis

            - name: REDIS_PORT
              value: "6379"

            - name: NOTIFICATION_STREAM
              value: notifications