apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis
  namespace: eventhub

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis
          image: redis:alpine
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 6379

          args:
            - redis-server
            - --appendonly
            - "no"

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"